# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rr4r_wrappers", use_symbols = TRUE, package_name = "rr4r")

#' @docType package
#' @usage NULL
#' @useDynLib rr4r, .registration = TRUE
NULL

#' Detect the presence or absence of a pattern in a string.
#' @param x
#'   A character vector to look for the patterns in.
#' @param pattern
#'   A pattern to look for.
#' @examples
#' fruit <- c("apple", "banana", "pear", "pinapple")
#' rr4r_detect(fruit, "a")
#' rr4r_detect(fruit, "^a")
#' rr4r_detect(fruit, "a$")
#' rr4r_detect(fruit, "b")
#' rr4r_detect(fruit, "[aeiou]")
#' @export
rr4r_detect <- function(x, pattern) .Call(wrap__rr4r_detect, x, pattern)

#' Extract matching patterns from a string.
#' @param x
#'   A character vector to look for the patterns in.
#' @param pattern
#'   A pattern to look for.
#' @examples
#' shopping_list <- c("apples x4", "bag of flour", "bag of sugar", "milk x2")
#' rr4r_extract(shopping_list, "\\d")
#' rr4r_extract(shopping_list, "[a-z]+")
#' rr4r_extract(shopping_list, "[a-z]{1,4}")
#' rr4r_extract(shopping_list, "\\b[a-z]{1,4}\\b")
#' @export
rr4r_extract <- function(x, pattern) .Call(wrap__rr4r_extract, x, pattern)

