# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rr4r_wrappers", use_symbols = TRUE, package_name = "rr4r")

#' @docType package
#' @usage NULL
#' @useDynLib rr4r, .registration = TRUE
NULL

#' Detect pattern
#' @export
rr4r_detect <- function(x, pattern) .Call(wrap__rr4r_detect, x, pattern)

